### PR TITLE
Frogtips

### PR DESCRIPTION
**Pull request by gwatt**

### CODE REVIEW

**Comment by cmhull42** [comment]
I won't be able to review for a few days, make SkySom do it if you want it sooner.

**Comment by Demannu** [comment]
I'll take a peek at it in a few hours. I believe SkySom is unavailable for
a few days

**Comment by SkySom** [comment]
SkySom is gone until next Friday. Connoor can screw himself

**Comment by coreymatyas** [comment]
Corey is actually here and able to review things, as is evidenced by the fact I just merged. Thanks for the pull request!

**Pull request merged**
